# Generated by validate_and_order_vocabularies.py
# Vocabularies ordered by ENCODE result count (most popular first)

# ASSAY_TYPES ordered by popularity
ASSAY_TYPES_ORDERED = {
    "ChIP-seq": "ChIP-seq (Chromatin Immunoprecipitation)",  # 12569 results
    "DNase-seq": "DNase-seq (Chromatin Accessibility)",  # 3582 results
    "RNA-seq": "RNA-seq (Transcriptome)",  # 1270 results
    "Mint-ChIP-seq": "Mint-ChIP-seq (Low-input ChIP)",  # 1162 results
    "polyA plus RNA-seq": "polyA plus RNA-seq (mRNA)",  # 943 results
    "shRNA knockdown followed by RNA-seq": "shRNA knockdown RNA-seq",  # 668 results
    "eCLIP": "eCLIP (RNA-Protein Binding)",  # 587 results
    "ATAC-seq": "ATAC-seq (Chromatin Accessibility)",  # 560 results
    "single-cell RNA sequencing assay": "scRNA-seq (Single-Cell Transcriptome)",  # 524 results
    "HiC": "HiC (Chromatin Conformation)",  # 501 results
    "CRISPR genome editing followed by RNA-seq": "CRISPR followed by RNA-seq",  # 470 results
    "microRNA-seq": "microRNA-seq (miRNAs)",  # 418 results
    "single-nucleus ATAC-seq": "snATAC-seq (Single-Nucleus Accessibility)",  # 370 results
    "transcription profiling by array assay": "Expression Array",  # 291 results
    "whole-genome shotgun bisulfite sequencing": "WGBS (Whole-Genome Bisulfite)",  # 278 results
    "DNA methylation profiling by array assay": "Methylation Array",  # 257 results
    "PRO-cap": "PRO-cap (Nascent Transcription)",  # 224 results
    "RRBS": "RRBS (Reduced Representation Bisulfite)",  # 218 results
    "small RNA-seq": "small RNA-seq (Small RNAs)",  # 216 results
    "RNA Bind-n-Seq": "RNA Bind-n-Seq",  # 216 results
    "ChIA-PET": "ChIA-PET (Chromatin Interaction)",  # 213 results
    "long read RNA-seq": "long read RNA-seq (Isoform)",  # 203 results
    "RAMPAGE": "RAMPAGE (TSS Mapping)",  # 168 results
    "comparative genomic hybridization by array": "CGH Array",  # 142 results
    "CAGE": "CAGE (TSS Mapping)",  # 121 results
    "Repli-seq": "Repli-seq (Replication Timing)",  # 119 results
    "microRNA counts": "microRNA counts",  # 115 results
    "siRNA knockdown followed by RNA-seq": "siRNA knockdown RNA-seq",  # 113 results
    "CRISPRi followed by RNA-seq": "CRISPRi followed by RNA-seq",  # 77 results
    "RIP-seq": "RIP-seq (RNA-Protein Binding)",  # 73 results
    "MRE-seq": "MRE-seq (Methylation)",  # 68 results
    "long read single-cell RNA-seq": "long read single-cell RNA-seq",  # 64 results
    "Repli-chip": "Repli-chip (Replication Timing)",  # 63 results
    "MeDIP-seq": "MeDIP-seq (Methylation)",  # 55 results
    "PAS-seq": "PAS-seq (PolyA Site)",  # 54 results
    "whole genome sequencing assay": "WGS (Whole Genome Sequencing)",  # 52 results
    "Bru-seq": "Bru-seq (Nascent Transcription)",  # 49 results
    "genetic modification followed by DNase-seq": "CRISPR-DNase",  # 46 results
    "FAIRE-seq": "FAIRE-seq (Chromatin Accessibility)",  # 37 results
    "polyA minus RNA-seq": "polyA minus RNA-seq (Non-polyA)",  # 32 results
    "BruChase-seq": "BruChase-seq (Nascent Transcription)",  # 32 results
    "RIP-chip": "RIP-chip (RNA-Protein Binding)",  # 32 results
    "RNA-PET": "RNA-PET (Transcript Boundaries)",  # 31 results
    "PRO-seq": "PRO-seq (Nascent Transcription)",  # 22 results
    "BruUV-seq": "BruUV-seq (Nascent Transcription)",  # 16 results
    "protein sequencing by tandem mass spectrometry assay": "MS/MS Proteomics",  # 14 results
    "5C": "5C (Chromatin Conformation)",  # 13 results
    "TAB-seq": "TAB-seq (5hmC Mapping)",  # 8 results
    "iCLIP": "iCLIP (RNA-Protein Binding)",  # 7 results
    "icSHAPE": "icSHAPE (RNA Structure)",  # 6 results
    "DNA-PET": "DNA-PET",  # 6 results
    "seqFISH": "seqFISH (Spatial Transcriptomics)",  # 5 results
    "GRO-cap": "GRO-cap (Nascent Transcription)",  # 4 results
    "SPRITE": "SPRITE (3D Chromatin)",  # 3 results
    "MNase-seq": "MNase-seq (Nucleosome Mapping)",  # 2 results
    "capture Hi-C": "capture Hi-C (Promoter Contacts)",  # 2 results
    "icLASER": "icLASER (RNA Structure)",  # 2 results
    "Switchgear": "Switchgear",  # 2 results
    "5' RLM RACE": "5' RLM RACE",  # 2 results
    "Circulome-seq": "Circulome-seq",  # 1 results
}

# Zero-result assays (consider removing):
# None

# BIOSAMPLES ordered by popularity
BIOSAMPLES_ORDERED = [
    "K562",  # 2571 results
    "HepG2",  # 1793 results
    "A549",  # 538 results
    "GM12878",  # 490 results
    "MCF-7",  # 356 results
    "heart",  # 328 results
    "HEK293",  # 291 results
    "liver",  # 286 results
    "SK-N-SH",  # 196 results
    "spleen",  # 196 results
    "lung",  # 165 results
    "HeLa-S3",  # 159 results
    "kidney",  # 156 results
    "brain",  # 127 results
    "IMR-90",  # 114 results
    "cerebellum",  # 111 results
    "thymus",  # 66 results
    "Caco-2",  # 44 results
    "PC-3",  # 33 results
    "U2OS",  # 8 results
    "Jurkat",  # 7 results
    "cortex",  # 2 results
]

# TARGETS ordered by popularity
TARGETS_ORDERED = [
    "H3K4me3",  # 854 results
    "H3K27ac",  # 757 results
    "H3K27me3",  # 718 results
    "H3K4me1",  # 691 results
    "H3K36me3",  # 672 results
    "H3K9me3",  # 643 results
    "CTCF",  # 608 results
    "POLR2A",  # 225 results
    "H3K9ac",  # 203 results
    "EP300",  # 97 results
    "RAD21",  # 83 results
    "H3K79me2",  # 56 results
    "H4K20me1",  # 54 results
    "SMC3",  # 22 results
]

# Working ENCODE API parameter paths:
# organism: replicates.library.biosample.donor.organism.scientific_name
# life_stage: replicates.library.biosample.life_stage
# target: target.label
